# Generated by Django 3.2 on 2021-05-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.CharField(max_length=255, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=255, null=True, verbose_name='Password'),
        ),
    ]
