# Generated by Django 3.2 on 2021-05-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210507_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
        migrations.AddField(
            model_name='account',
            name='api_key',
            field=models.CharField(max_length=24, null=True, verbose_name='API_KEY'),
        ),
        migrations.AddField(
            model_name='account',
            name='api_secret',
            field=models.CharField(max_length=48, null=True, verbose_name='API_SECRET'),
        ),
    ]
