# Generated by Django 3.2 on 2021-05-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210507_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='api_key',
            field=models.CharField(max_length=24, verbose_name='API_KEY'),
        ),
        migrations.AlterField(
            model_name='account',
            name='api_secret',
            field=models.CharField(max_length=48, verbose_name='API_SECRET'),
        ),
    ]
