# Generated by Django 3.2 on 2021-05-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20210508_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
    ]
