# Generated by Django 3.2.2 on 2021-05-10 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20210508_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='order_api_key',
            new_name='api_key',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='order_api_secret',
            new_name='api_secret',
        ),
        migrations.RemoveField(
            model_name='account',
            name='order_cancel_api_key',
        ),
        migrations.RemoveField(
            model_name='account',
            name='order_cancel_api_secret',
        ),
    ]
