# Generated by Django 3.2.2 on 2021-05-12 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20210510_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderID', models.IntegerField()),
                ('symbol', models.CharField(max_length=25)),
                ('volume', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('side', models.IntegerField(choices=[(0, 'Buy'), (1, 'Sell')])),
                ('price', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.account')),
            ],
        ),
    ]
