# Generated by Django 3.2.2 on 2021-05-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderID',
            field=models.CharField(max_length=36),
        ),
    ]
