# Generated by Django 3.2.2 on 2021-05-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_order_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='side',
            field=models.CharField(max_length=4),
        ),
    ]
